parameters:
  - name: environment
    displayName: Name of the environment to deploy to
    type: string
  - name: region
    displayName: Name of AWS region to deploy into
    type: string
  - name: stateBucketName
    displayName: Name of the S3 bucket name for the state file
    type: string
  - name: stateLockTableName
    displayName: Name of the DynamoDB table name for state locking
    type: string
  - name: serviceConnectionName
    displayName: Service connection name, used for init & plan
    type: string

jobs:
  - job: plan
    displayName: Plan
    steps:
      - template: aws/terraform/plan.yml@templates
        parameters:
          artifactName: ${{ parameters.environment }}_${{ parameters.region }}
          planAdditionalCommandOptions: '-var-file=variables/${{ parameters.environment }}.${{ parameters.region }}.tfvars'
          serviceConnectionName: ${{ parameters.serviceConnectionName }}
          stateBucketName: ${{ parameters.stateBucketName }}
          stateLockTableName: ${{ parameters.stateLockTableName }}
          workspaceName: expensely-io-${{ parameters.environment }}
  - template: job/approve.yml@templates
    parameters:
      dependsOn: plan
      timeoutInMinutes: 60
      notifyUsers: '[Expensely]\Expensely Team'
  - deployment: apply
    displayName: Apply
    dependsOn: approve
    environment: ${{ parameters.environment }}
    strategy:
      runOnce:
        deploy:
          steps:
            - download: none
            - template: aws/terraform/apply.yml@templates
              parameters:
                artifactName: ${{ parameters.environment }}_${{ parameters.region }}
                serviceConnectionName: ${{ parameters.serviceConnectionName }}
